name: "Nomad Dispatch"
description: "Dispatch a HashiCorp Nomad parameterized job via Nomad CLI (composite action)."
author: "nomad-dispatch maintainers"

inputs:
  nomad_addr:
    description: "Nomad HTTP address (e.g., https://nomad.example.com:4646)"
    required: true
  nomad_token:
    description: "Nomad ACL token (required unless using OIDC authentication)"
    required: false
    default: ""
  oidc_enable:
    description: "Enable OIDC authentication to get Nomad token from GitHub"
    required: false
    default: "false"
  oidc_audience:
    description: "OIDC audience for token request (default: nomad.example.com)"
    required: false
    default: "nomad.example.com"
  oidc_debug:
    description: "Enable debug output for OIDC authentication responses"
    required: false
    default: "false"
  job_name:
    description: "Parameterized Nomad job name to dispatch"
    required: true
  payload:
    description: "Optional raw string payload (will be base64 encoded)"
    required: false
    default: ""
  meta:
    description: "Optional metadata as YAML object or JSON string (e.g., key1: val1, key2: val2 or {\"key1\":\"val1\"})"
    required: false
    default: "{}"
  region:
    description: "Optional Nomad region"
    required: false
    default: ""
  namespace:
    description: "Optional Nomad namespace"
    required: false
    default: ""
  tls_skip_verify:
    description: "Skip TLS verification (insecure)"
    required: false
    default: "false"
  ca_pem:
    description: "Optional CA certificate content (PEM)"
    required: false
    default: ""
  client_cert:
    description: "Optional client certificate content (PEM)"
    required: false
    default: ""
  client_key:
    description: "Optional client private key content (PEM)"
    required: false
    default: ""
  dry_run:
    description: "Print request and exit without dispatching"
    required: false
    default: "false"
  dispatch_debug:
    description: "Enable debug output to show the actual nomad command before execution"
    required: false
    default: "false"
  nomad_version:
    description: "Nomad CLI version to install via hashicorp/setup-nomad (e.g., 'latest' or '1.8.3')"
    required: false
    default: "latest"

outputs:
  dispatched_job_id:
    description: "The dispatched job ID"
    value: ${{ steps.dispatch.outputs.dispatched_job_id }}
  eval_id:
    description: "The evaluation ID"
    value: ${{ steps.dispatch.outputs.eval_id }}
  status:
    description: "Final status: dispatched"
    value: ${{ steps.dispatch.outputs.status }}

runs:
  using: composite
  steps:
    - name: Setup Nomad CLI
      uses: hashicorp/setup-nomad@main
      with:
        version: ${{ inputs.nomad_version }}

    - name: Verify prerequisites
      shell: bash
      run: |
        set -euo pipefail
        command -v curl >/dev/null || { echo "curl is required"; exit 1; }
        command -v jq >/dev/null || { echo "jq is required"; exit 1; }
        # Nomad CLI is required and used for all dispatch operations
        command -v nomad >/dev/null && nomad version || true

    - name: Nomad Dispatch
      id: dispatch
      shell: bash
      env:
        NOMAD_ADDR: ${{ inputs.nomad_addr }}
        NOMAD_TOKEN: ${{ inputs.nomad_token }}
        OIDC_ENABLE: ${{ inputs.oidc_enable }}
        OIDC_AUDIENCE: ${{ inputs.oidc_audience }}
        OIDC_DEBUG: ${{ inputs.oidc_debug }}
        JOB_NAME: ${{ inputs.job_name }}
        PAYLOAD: ${{ inputs.payload }}
        META: ${{ inputs.meta }}
        REGION: ${{ inputs.region }}
        NAMESPACE: ${{ inputs.namespace }}
        TLS_SKIP_VERIFY: ${{ inputs.tls_skip_verify }}
        CA_PEM: ${{ inputs.ca_pem }}
        CLIENT_CERT: ${{ inputs.client_cert }}
        CLIENT_KEY: ${{ inputs.client_key }}
        DRY_RUN: ${{ inputs.dry_run }}
        DISPATCH_DEBUG: ${{ inputs.dispatch_debug }}
      run: |
        bash "${{ github.action_path }}/scripts/dispatch.sh"
