name: CI

on:
  workflow_dispatch:

jobs:
  dry-run-basic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run basic dispatch
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "noop"
          dry_run: true

  dry-run-with-meta:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with meta
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "test payload with meta"
          meta: |
            env: test
            version: "1.0"
            debug: "true"
          dry_run: true

  dry-run-with-meta-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with meta (JSON backward compatibility)
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "test payload with JSON meta"
          meta: '{"env":"production","version":"2.0","feature_flag":"enabled"}'
          dry_run: true

  dry-run-with-region-namespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with region and namespace
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "regional job"
          region: us-west-2
          namespace: production
          dry_run: true

  dry-run-with-tls-options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with TLS options
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "secure job"
          tls_skip_verify: true
          ca_pem: |
            -----BEGIN CERTIFICATE-----
            MIICDummy...ExampleCAContent...
            -----END CERTIFICATE-----
          dry_run: true

  dry-run-with-client-certs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with client certificates
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "authenticated job"
          client_cert: |
            -----BEGIN CERTIFICATE-----
            MIICDummy...ExampleClientCertContent...
            -----END CERTIFICATE-----
          client_key: |
            -----BEGIN PRIVATE KEY-----
            MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC...DummyKey...
            -----END PRIVATE KEY-----
          dry_run: true

  dry-run-with-wait-params:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with wait parameters
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "waiting job"
          wait: true
          wait_timeout: 600
          print_logs: true
          task_name: main
          dry_run: true

  dry-run-empty-payload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with empty payload
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          dry_run: true

  dry-run-different-nomad-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with specific Nomad version
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "version test"
          nomad_version: "1.8.3"
          dry_run: true

  dry-run-with-oidc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with OIDC authentication
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          oidc_enable: true
          oidc_audience: nomad.example.com
          job_name: dummy-job
          payload: "OIDC authenticated job"
          meta: |
            auth_method: oidc
            github_actor: ${{ github.actor }}
          dry_run: true

  dry-run-with-oidc-debug:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with OIDC debug enabled
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          oidc_enable: true
          oidc_audience: nomad.example.com
          oidc_debug: true
          job_name: dummy-job
          payload: "OIDC debug test"
          meta: |
            debug_mode: enabled
            test_type: oidc_debug
          dry_run: true

  dry-run-comprehensive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with comprehensive parameters
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "comprehensive test with all options"
          meta: |
            test_type: comprehensive
            parameters: all
            build_number: 12345
          region: global
          namespace: testing
          tls_skip_verify: false
          wait: true
          wait_timeout: 120
          print_logs: false
          nomad_version: latest
          dry_run: true

  dry-run-with-command-debug:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with command debug enabled
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "debug test payload"
          meta: |
            debug_enabled: true
            test_type: command_debug
          region: us-east-1
          namespace: debug
          command_debug: true
          dry_run: true

  dry-run-with-meta-spaces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with meta values containing spaces
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "test with spaced meta values"
          meta: |
            user_cmd: echo "hello from github"
            description: test with multiple spaces
            script_path: /path/to script with spaces.sh
          command_debug: true
          dry_run: true

  dry-run-with-meta-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dry-run dispatch with meta values containing quotes
        uses: ./
        with:
          nomad_addr: https://example.invalid:4646
          nomad_token: dummy
          job_name: dummy-job
          payload: "test with quoted meta values"
          meta: |
            single_quote_cmd: echo 'hello from github'
            backtick_cmd: echo `hello from github`
            mixed_quotes: echo "hello" 'world' `test`
            complex_script: /path/to/script 'with quotes'.sh
          command_debug: true
          dry_run: true

